import type { Metadata } from 'next';
import '@/styles/globals.css';
import { Raleway } from 'next/font/google';

import Header from '@/components/Header';
import SideBar from '@/components/SideBar';
import StyledComponentsRegistry from '@/lib/AntdRegistry';
import Nav from '@/components/Nav';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Movie Dashboard',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className + ' overscroll-none'}>
        <StyledComponentsRegistry>
          <Header />
          <div className="flex mt-[calc(h-20)]">
            <SideBar position="left">
              <Nav />
            </SideBar>
            <div className="grow lg:mx-[calc(var(--sidebar-width))] transition-[margin]">
              {children}
            </div>
            <SideBar position="right">
              <div>Side bar</div>
            </SideBar>
          </div>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
