import type { Metadata } from 'next';
import '@/styles/globals.css';
import { Raleway } from 'next/font/google';

import { NavContextProvider } from '@/context/navContext';
import Layout from '@/components/Layout';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Movie Dashboard',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body className={raleway.className + ' overscroll-none'}>
        <NavContextProvider>
          <Layout>{children}</Layout>
        </NavContextProvider>
      </body>
    </html>
  );
}
